src/raven_clj/core.clj, test/raven_clj/core_test.clj
Previously, if you passed something like
{:foo {:bar "baz"}}
as `:extra` data, Sentry would receive it as
{"foo": [["bar", "baz"]]}
There's not any real harm in this, it just looks a little surprising/clunky in the UI.
This commit changes the handling of `:extra` maps so that nested map values are recursively turned into `java.util.HashMap` objects. This ensures Sentry receives those nested maps as JSON objects, which makes the data look a bit tighter in the UI.
n.b.: It looks like the current behavior is a consequence of Clojure maps implementing both `java.lang.Iterable` and `java.util.Map`. The `JsonMarshaller` in raven-java[^1] treats Iterables and Maps as mutually exclusive; it just happens to check if serializable values are Iterable first.
[^1]: https://git.io/vyB79
=> Send Clojure maps nested in :extra as HashMaps

src/raven_clj/core.clj
Fairly straightforward hint, I took a shot at the other functions that are reflecting, but got a bit stumped at why they are causing reflection. I want to revisit them later, but for now just wanted to get the path I actually hit the most addressed.
=> Fix reflection in java-util-hashmappify-vals

README.md, project.clj, src/sentry_clj/core.clj, src/sentry_clj/internal.clj, src/sentry_clj/ring.clj, test/sentry_clj/core_test.clj, test/sentry_clj/internal_test.clj, test/sentry_clj/ring_test.clj
`sentry-java` 1.0.0 is a renaming and large refactor of `raven-java`. This PR *only* switches over to the new library version and handles the renames.
As a followup, I'm going to submit one to use the new (simpler/cleaner) event APIs. As you're well aware, the APIs in `raven-java` were funktastic. 😄 
I'm also interested in pulling this into the `getsentry` organization if possible. I'd like to point Clojure users to this library and I don't want you to be burdened with issues.
=> Update to sentry-java 1.0.0

src/sentry_clj/core.clj
Looks like some find/replace fallout with the change from raven-clj to sentry-clj and raven-java to sentry-java.
sentry-java 1.0.0 doesn't have a SentryClientFactory.createSentryInstance: https://github.com/getsentry/sentry-java/blob/087ccf0fd3d215044367f146ef9fe59200d5b183/sentry/src/main/java/io/sentry/SentryClientFactory.java#L75
=> sentry-clj.core: fix createSentryClient name error

src/sentry_clj/ring.clj, test/sentry_clj/ring_test.clj
The ring exception handler wrapper treats sentry/send-event as if it expects 2 args. Was this previously the case? It seems dsn is now inferred deeper in the call stack.
With these changes my handler is reporting properly in production.
=> Wrap report exceptions bug

project.clj
The current version of the API sends a `InvalidDsnException Invalid DSN, the following properties aren't set '[secret key]'  io.sentry.dsn.Dsn.validate (Dsn.java:212)` thus I took the liberty and updated the Java API version
=> bump java version to include new DSN style

CHANGELOG.md, deps.edn, pom.xml, src/sentry_clj/core.clj
Also, bring compatibility up to Sentry Java 3.1.0.
Drops an unnecessary dependency on Cheshire (only used for testing)
-=david=-
=> Use `production` as default

src/sentry_clj/core.clj
Hi Sentry!
not sure if you accept PRs or if this is the right place for this.
i found something that is pretty annoying, It happened a couple of times to me (in production too).
I was using the simplest `send-event` form possible, like this:
```clojure
(sentry-clj.core/capture-event {:message "My error message"})
```
since the message is a simple string instead of a map, sentry-clj reply with an event ID but nothing arrives in my project on sentry.io.
Using this form `(send-event {:message {:message "Msg"}})` seems not only useless but also easy to get wrong.
I often use `capture-event` with a raw string and very rarely with a formatted one.
I see this behaviour changed since version 3.1.135, the events sent with this kind of message are ingested by the server and displayed in my project …
=> Convert a simple string message into a map to avoid losing events.

src/sentry_clj/ring.clj, test/sentry_clj/ring_test.clj
According to ring [SPEC](https://github.com/ring-clojure/ring/blob/99ece0b95293c6b45e1bdb03a99ab1d597117ac9/SPEC#L73), the key with the request method is called `:request-method`, but the tests were referencing it as `:method`.
The following error (sentry-java expects a String and not a Keyword as HTTP method) was never thrown on tests because of this mistaken setup fixture.
```
Exception: java.lang.ClassCastException: class clojure.lang.Keyword cannot be cast to class java.lang.String (clojure.lang.Keyword is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
```
This PR fixes the test setup and the bug
=> fix: request method as string

README.md, src/sentry_clj/core.clj, test/sentry_clj/core_test.clj
Right now if you send a number of breadcrumbs with an event, they'll all end up on the server with identical timestamps so won't be viewable in chronological order. This PR adds support for an optional explicit `:timestamp` key in breadcrumbs so you can keep track of when breadcrumbs actually happened. It accepts a `java.util.Date` like the underlying sentry-java, although Sentry does support more precision than this.
=> Breadcrumb timestamps

src/sentry_clj/tracing.clj, test/sentry_clj/tracing_test.clj
Hi. I''m sorry for sending pull requests repeatedly.
I've made two changes to  the `with-start-child-span` macro
One is that you can get the forms evaluation result which is given as arguments in child span.
Another is that you can evaluate forms even if no tracing setting.
=> Fix enable to get evaluation result in a child span.

CHANGELOG.md, src/sentry_clj/ring.clj, test/sentry_clj/ring_test.clj
It can be used for instance to prune personally identifiable information from requests.
=> Extend wrap-sentry-tracing with custom req preprocess fn

README.md, src/sentry_clj/core.clj, test/sentry_clj/core_test.clj
Added `:instrumenter` and `:event-processors` config options to expose `SentryOptions.setInstrumenter` and `SentryOptions.addEventProcessor`.
Useful when configuring OpenTelemetry for Sentry.
=> Add instrumenter and event-processors config options

src/sentry_clj/core.clj
Allows passing through the logger & diagnostic level, for finer logging control.
=> Allow setting logger & diagnostic level

src/sentry_clj/core.clj, test/sentry_clj/core_test.clj
Without this patch, keys with different namespaces but equal names would non-deterministically clobber each other. Also, namespaces may provide valuable context, so preserving them is generally useful.
=> Preserve keyword namespaces in java-util-hashmappify-vals

src/sentry_clj/core.clj, test/sentry_clj/core_test.clj
Instead of only adding ex-data of the top-level exception into the extra map, walk down the cause chain and add all ex-data encountered therein. To prevent them from clobbering each other or any keys already present in the extra map, nest all ex-data under separate keys. The top-level exception's ex-data is added under "ex-data" while causes are added under `"ex-data, cause <n>: <message>"` where `<n>` is the cause's position in the chain and `<message>` is its message.
=> Preserve ex-data of all ex-info exceptions in the cause chain

README.md, src/sentry_clj/core.clj
When sentry gets initialized, if no option is passed (no-arg `Sentry.init()`), it will call `setEnableExternalConfiguration` with `true`.
The clj library should allow supplying the same option.
=> Allow enabling external configuration

src/sentry_clj/core.clj
Hello, Sentry.
I’m not sure if I can make a pull request here, but I found an issue when handling sentry-clj with AWS Lambda. The issue is that Sentry event is being shut down by serverless during execution.
I added the flush function, which was updated in sentry-java in 2021, to enable synchronous flushing of Sentry events for AWS Lambda environments. This ensures that all events are sent before the serverless execution is completed, addressing the issue of events not being sent.
https://github.com/getsentry/sentry-java/issues/1023
Thanks for your nice tool.
=> Add ability to flush events synchronously

src/sentry_clj/core.clj, test/sentry_clj/core_test.clj
Change `java-util-hashmappify-vals` to also change keywords to strings for lone values nested under a map's direct values.
When `postwalk` would encounter a non-map value, the value would be returned as-is.  This means a keyword which would be nested inside another non-map structure would not be converted to a string.  For maps, if the keys or values are keywords themselves, it would always directly convert them into strings, which masked the problem.
This results in weird-looking serialization which exposes the underlying Java Keyword object, as per #67.
=> Ensure all keywords are stringified by java-util-hashmappify-vals

src/sentry_clj/core.clj, test/sentry_clj/core_test.clj
This simplifies the code as we don't have to use an extra walk.
=> Also convert outer maps into HashMap in java-util-hashmappify-vals

src/sentry_clj/core.clj, src/sentry_clj/logging.clj, test/sentry_clj/core_test.clj, test/sentry_clj/logging_test.clj
Features implemented in this request:
- ability to enable logs on init
- support setBeforeSend for log events
- all specific logging functions by level and a generic one
- tests
Resolves #73
=> Support Sentry structured logging 

README.md
This PR adds a missing documentation for Logs to the README.md file.
=> Add documentation for logs to README
